### ISSUE TITLE
Steno should output error message when port 3000 is already in use

### ISSUE THREAD

**Issue by wilhelmklopp** [slackapi/steno#46]
### Description

When there's already something else running on port 3000, steno will crash without a proper error message.

Suggestion: Show an error message like "Port 3000 is already in use, choose a different port by specifying `--out-port` explicitly"

```
Control API started on port 4000
Scenario: unfurl
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server.setupListenHandle [as _listen2] (net.js:1305:14)
    at listenInCluster (net.js:1353:12)
    at Server.listen (net.js:1453:7)
    at Server.<anonymous> (internal/util.js:229:26)
    at HttpProxy.listen (/snapshot/steno/dist/record/http-proxy.js:116:29)
    at Recorder.start (/snapshot/steno/dist/record/recorder.js:31:32)
    at RecordingController.start (/snapshot/steno/dist/record/controller.js:36:27)
    at Object.startRecordingController (/snapshot/steno/dist/record/controller.js:103:23)
```

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/steno/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

steno version: 1.0.0

OS version(s): mac OS High Sierra

#### Steps to reproduce:

1. Have something running on port 3000
2. Start Steno
3. See bug

Additional suggestion:
Since a lot of node projects use port 3000 by default, maybe it would make sense to change the default steno port to a different port that is less commonly used.

**Comment by aoberoi** [comment]
thanks for the report! let's definitely get the error message in, changing the default port could come down the line if others find this equally annoying.

**Comment by aoberoi** [comment]
not the best, but i would have expected the following catch clause to give a slightly better error message:

https://github.com/slackapi/steno/blob/ad3f888274f33146b0a84461cf0b38db9d0d7e24/src/record/recorder.ts#L67-L70

clearly, something is going wrong with the following lines:

https://github.com/slackapi/steno/blob/ad3f888274f33146b0a84461cf0b38db9d0d7e24/src/record/http-proxy.ts#L148-L149
