### ISSUE TITLE
Connection Refused with --app container:80

### ISSUE THREAD

**Issue by leenooks** [slackapi/steno#62]
### Description

Hi, I'm running steno in a container using the node:9.11.1 image:
`node node_modules/steno/bin/./steno --record --app slackbot_nginx:80 --out-port 3000 --in-port 3080 --scenario-dir /test/steno`

However, incoming queries are never forwarded.

```
www-data@24dc124ff300:~/html$ curl -I http://localhost:3080/api/events
HTTP/1.1 502 Bad Gateway
Date: Fri, 11 May 2018 03:53:06 GMT
Connection: keep-alive
```

The respective test file shows this:
```
HEAD /api/events HTTP/1.1
user-agent: curl/7.38.0
host: localhost:3080
accept: */*

""

-----

HTTP/1.1 502 Bad Gateway


"Steno failed to connect to slackbot_nginx:80"
```

However, from the container in question - I can connect to the app:
```
www-data@24dc124ff300:~/html$ curl -I slackbot_nginx:80/api/events
HTTP/1.1 405 Method Not Allowed
Server: nginx/1.13.12
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
X-Powered-By: PHP/7.2.5
allow: POST
Cache-Control: no-cache, private
date: Fri, 11 May 2018 03:54:34 GMT
```
(The 405 is OK, because I didnt sent any data with the test.)

What am I missing?

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [X] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/steno/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

#### Reproducible in:

steno version: 1.2.0

**Comment by aoberoi** [comment]
@leenooks i believe the problem is that steno doesn't know how to normalize `"slackbot_nginx:80"` into a URL. can you try adding a protocol to the argument like `"http://slackbot_nginx:80"`?

it might be worth building support for this directly into steno so you don't have to add the protocol. at the moment, `localhost` will work and assume `http://`. this might actually be a feature request for the underly [`normalize-url`](https://www.npmjs.com/package/normalize-url) package.

**Comment by leenooks** [comment]
That was it - thank you. (Wish I thought of it). Adding the protocol to the URL fixed it. 👍
