### ISSUE TITLE
Fix code quality issues

### ISSUE THREAD

**Issue by withshubh** [slackapi/steno#79]
### Description

Hi :wave: I ran the [DeepSource](https://deepsource.io) static analyzer on the forked copy of this repo and found some [interesting code quality issues](https://deepsource.io/gh/withshubh/steno/issues/). Fixing these issues will resolve potential bugs and anti-patterns in code.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] enhancement (feature request)

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/steno/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

**Comment by seratch** [comment]
Hi, thanks for the suggestion! However, we are not planning to use the tool for this project at this time. It'd be appreciated if you could understand this.
