### ISSUE TITLE
Cannot record incoming requests in socket mode

### ISSUE THREAD

**Issue by kitti-radovics** [slackapi/steno#87]
### Description

Hi,
I'm using socket mode for connecting my app to Slack and in this case no tunneling is set up for incoming requests (because it's not needed). How can I make Slack to send requests through Steno so that I can record incoming requests too?

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x ] I've read and understood the [Contributing guidelines](https://github.com/slackapi/steno/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x ] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x ] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by srajiang** [comment]
Hi @kitti-radovics 👋  
Thanks so much for writing in! This would be a feature extension. Unfortunately, we're not actively maintaining Steno as a team anymore, so we're not going to be able to support this request at this time. 

We are hoping to introduce a new testing option down the line that will replace this functionality and more, though we don't have a timeline on this as of yet.
